### ISSUE TITLE
[15pt] Add Redux

### ISSUE THREAD

**Issue by christianonoh** [christianonoh/vecs-school-backend#12]
- Create store
- Create reducers and its functions
- Connect store to application
- Consume data from store in application
- Dispatch actions from necessary buttons to the reducer

**Comment by vvoo21** [comment]
Add User Redux:
https://github.com/smunoz1988/vecs-school-frontend/pull/5

**Comment by smunoz1988** [comment]
Add course Redux:
https://github.com/smunoz1988/vecs-school-frontend/pull/6

**Comment by vvoo21** [comment]
Add reservation Redux:

https://github.com/smunoz1988/vecs-school-frontend/pull/7
