### ISSUE TITLE
[2pt] Integrate the Backend and Frontend

### ISSUE THREAD

**Issue by christianonoh** [christianonoh/vecs-school-backend#13]
- Use Axios or similar library to make API requests
- Make API requests to the backend
- Display fetched data in React components.

**Comment by smunoz1988** [comment]
Issue closed with PR:

https://github.com/smunoz1988/vecs-school-frontend/pull/7
https://github.com/smunoz1988/vecs-school-frontend/pull/6
https://github.com/smunoz1988/vecs-school-frontend/pull/5
